// angular/src/app/@theme/layouts/footer/footer.component.ts
// angular import
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {}

<footer class="theme-footer">
  <div class="footer-wrapper">
    <div class="flex align-item-center">
      <div class="col m-t-5 m-b-5">
        <p class="m-0">
          © Able Pro crafted with ♥ by Team
          <a href="https://themeforest.net/user/phoenixcoded" target="_blank">Phoenixcoded</a>
        </p>
      </div>
      <div class="col-auto">
        <ul class="list-inline footer-link m-b-0">
          <li class="list-inline-item">
            <a href="https://ableproadmin.com/">Home</a>
          </li>
          <li class="list-inline-item">
            <a href="https://codedthemes.gitbook.io/able-pro-angular/" target="_blank">Documentation</a>
          </li>
          <li class="list-inline-item">
            <a href="https://phoenixcoded.authordesk.app/" target="_blank">Support</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

// react/src/layout/MainLayout/Footer.js
import { Link as RouterLink } from 'react-router-dom';

// material-ui
import { Link, Stack, Typography } from '@mui/material';

// ==============================|| MAIN LAYOUT - FOOTER ||============================== //

const Footer = () => (
  <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ p: '24px 16px 0px', mt: 'auto' }}>
    <Typography variant="caption">&copy; Able Pro ♥ crafted by Team Phoenixcoded</Typography>
    <Stack spacing={1.5} direction="row" justifyContent="space-between" alignItems="center">
      <Link component={RouterLink} to="https://ableproadmin.com" target="_blank" variant="caption" color="textPrimary">
        Home
      </Link>
      <Link
        component={RouterLink}
        to="https://codedthemes.gitbook.io/able-pro-react/"
        target="_blank"
        variant="caption"
        color="textPrimary"
      >
        Documentation
      </Link>
      <Link component={RouterLink} to="https://phoenixcoded.authordesk.app/" target="_blank" variant="caption" color="textPrimary">
        Support
      </Link>
    </Stack>
  </Stack>
);

export default Footer;
