// vue/src/views/widgets/chart/components/ProjectOverview.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import SvgSprite from '@/components/shared/SvgSprite.vue';
import { useTheme } from 'vuetify';

const theme = useTheme();
const primaryColor = theme.current.value.colors.primary;
const errorColor = theme.current.value.colors.error;

const menulist = ref(['Today', 'Weekly', 'Monthly']);

const chartOptions = computed(() => {
  return {
    chart: {
      type: 'area',
      height: 60,
      fontFamily: `inherit`,
      foreColor: 'rgba(var(--v-theme-lightText), var(--v-high-opacity))',
      toolbar: false,
      stacked: true,
      sparkline: {
        enabled: true
      },
      offsetX: -20
    },
    colors: [primaryColor],
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    dataLabels: {
      enabled: false
    },
    fill: {
      type: 'gradient',
      gradient: {
        shadeIntensity: 1,
        type: 'vertical',
        inverseColors: false,
        opacityFrom: 0.5,
        opacityTo: 0
      }
    },
    stroke: { curve: 'smooth', width: 2 },
    grid: {
      show: false
    },
    xaxis: {
      labels: {
        show: false
      },
      axisBorder: {
        show: false
      },
      axisTicks: {
        show: false
      }
    },
    yaxis: {
      labels: {
        show: false
      },
      axisBorder: {
        show: false
      },
      axisTicks: {
        show: false
      }
    },
    legend: {
      show: true
    },
    tooltip: {
      x: {
        show: false
      }
    }
  };
});

const areaChart = {
  series: [
    {
      name: 'Orders',
      data: [5, 25, 3, 10, 4, 50, 0]
    }
  ]
};

const chartOptions1 = computed(() => {
  return {
    chart: {
      type: 'area',
      height: 60,
      fontFamily: `inherit`,
      foreColor: 'rgba(var(--v-theme-lightText), var(--v-high-opacity))',
      toolbar: false,
      stacked: true,
      sparkline: {
        enabled: true
      },
      offsetX: -20
    },
    colors: [errorColor],
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    dataLabels: {
      enabled: false
    },
    fill: {
      type: 'gradient',
      gradient: {
        shadeIntensity: 1,
        type: 'vertical',
        inverseColors: false,
        opacityFrom: 0.5,
        opacityTo: 0
      }
    },
    stroke: { curve: 'smooth', width: 2 },
    grid: {
      show: false
    },
    xaxis: {
      labels: {
        show: false
      },
      axisBorder: {
        show: false
      },
      axisTicks: {
        show: false
      }
    },
    yaxis: {
      labels: {
        show: false
      },
      axisBorder: {
        show: false
      },
      axisTicks: {
        show: false
      }
    },
    legend: {
      show: true
    },
    tooltip: {
      x: {
        show: false
      }
    }
  };
});

const areaChart1 = {
  series: [
    {
      name: 'Orders',
      data: [0, 50, 4, 10, 3, 25, 5]
    }
  ]
};
</script>
<template>
  <v-card variant="outlined" class="bg-surface" rounded="lg">
    <v-card-text>
      <div class="d-flex justify-space-between align-center">
        <h5 class="text-h5 mb-0">Project overview</h5>
        <v-menu width="150" location="start">
          <template v-slot:activator="{ props }">
            <v-btn icon color="secondary" aria-label="menu" variant="text" rounded="md" size="small" v-bind="props">
              <SvgSprite name="custom-more-outline" style="width: 20px; height: 20px" />
            </v-btn>
          </template>
          <v-list elevation="24" class="pa-3" rounded="md" aria-label="menu" aria-busy="true">
            <v-list-item density="compact" rounded="md" color="secondary" v-for="(item, index) in menulist" :key="index" :value="index">
              <v-list-item-title class="text-h6 text-lightText">{{ item }}</v-list-item-title>
            </v-list-item>
          </v-list>
        </v-menu>
      </div>
    </v-card-text>
    <v-card-item class="pt-0">
      <v-row>
        <v-col cols="12" md="4" sm="6">
          <v-row class="align-end">
            <v-col cols="6">
              <p class="text-body-1 mb-0">Total Tasks</p>
              <h5 class="text-h5 mb-0">34,686</h5>
            </v-col>
            <v-col cols="6">
              <apexchart type="area" height="60" :options="chartOptions" :series="areaChart.series"> </apexchart>
            </v-col>
          </v-row>
        </v-col>
        <v-col cols="12" md="4" sm="6">
          <v-row class="align-end">
            <v-col cols="6">
              <p class="text-body-1 mb-0">Pending Tasks</p>
              <h5 class="text-h5 mb-0">3,6786</h5>
            </v-col>
            <v-col cols="6">
              <apexchart type="area" height="60" :options="chartOptions1" :series="areaChart1.series"> </apexchart>
            </v-col>
          </v-row>
        </v-col>
        <v-col cols="12" md="4">
          <v-btn color="primary" variant="flat" block rounded="md" size="large">
            <template v-slot:prepend>
              <SvgSprite name="custom-plus" style="width: 20px; height: 20px" />
            </template>
            Add Project
          </v-btn>
        </v-col>
      </v-row>
    </v-card-item>
  </v-card>
</template>

// react/src/sections/dashboard/ProjectOverview.js
import PropTypes from 'prop-types';
import { useEffect, useState } from 'react';

// material-ui
import { Button, useTheme } from '@mui/material';
import { Grid, ListItemButton, Menu, Stack, Typography } from '@mui/material';

// third-party
import ReactApexChart from 'react-apexcharts';

// project-imports
import MainCard from 'components/MainCard';
import IconButton from 'components/@extended/IconButton';

// assets
import { Add, More } from 'iconsax-react';

// ==============================|| CHART ||============================== //

const TaskStatusChart = ({ color, data }) => {
    const theme = useTheme();

    // chart options
    const areaChartOptions = {
        chart: {
            id: 'new-stack-chart',
            type: 'area',
            stacked: true,
            sparkline: {
                enabled: true
            }
        },
        plotOptions: {
            bar: {
                borderRadius: 0
            }
        },
        dataLabels: {
            enabled: false
        },

        fill: {
            type: 'gradient',
            gradient: {
                shadeIntensity: 1,
                type: 'vertical',
                inverseColors: false,
                opacityFrom: 0.5,
                opacityTo: 0
            }
        },
        stroke: { curve: 'smooth', width: 2 },
        tooltip: {
            x: {
                show: false
            }
        },
        grid: {
            show: false
        }
    };
    const { primary, secondary } = theme.palette.text;
    const line = theme.palette.divider;

    const [options, setOptions] = useState(areaChartOptions);

    useEffect(() => {
        setOptions((prevState) => ({
            ...prevState,
            colors: [color]
        }));
    }, [color, primary, secondary, line, theme]);

    const [series] = useState([{ name: 'Orders', data }]);

    return <ReactApexChart options={options} series={series} type="area" height={60} />;
};

TaskStatusChart.propTypes = {
    color: PropTypes.string,
    data: PropTypes.object
};
// ==============================|| CHART - PROJECT OVERVIEW ||============================== //

const ProjectOverview = () => {
    const theme = useTheme();
    const [anchorEl, setAnchorEl] = useState(null);

    const open = Boolean(anchorEl);

    const handleClick = (event) => {
        setAnchorEl(event.currentTarget);
    };

    const handleClose = () => {
        setAnchorEl(null);
    };

    return (
        <MainCard>
            <Stack direction="row" alignItems="center" justifyContent="space-between" spacing={1}>
                <Typography variant="h5">Project overview</Typography>
                <IconButton
                    color="secondary"
                    id="wallet-button"
                    aria-controls={open ? 'wallet-menu' : undefined}
                    aria-haspopup="true"
                    aria-expanded={open ? 'true' : undefined}
                    onClick={handleClick}
                >
                    <More />
                </IconButton>
                <Menu
                    id="wallet-menu"
                    anchorEl={anchorEl}
                    open={open}
                    onClose={handleClose}
                    MenuListProps={{
                        'aria-labelledby': 'wallet-button',
                        sx: { p: 1.25, minWidth: 150 }
                    }}
                    anchorOrigin={{
                        vertical: 'bottom',
                        horizontal: 'right'
                    }}
                    transformOrigin={{
                        vertical: 'top',
                        horizontal: 'right'
                    }}
                >
                    <ListItemButton onClick={handleClose}>Today</ListItemButton>
                    <ListItemButton onClick={handleClose}>Weekly</ListItemButton>
                    <ListItemButton onClick={handleClose}>Monthly</ListItemButton>
                </Menu>
            </Stack>
            <Grid container spacing={3} sx={{ mt: 1 }}>
                <Grid item xs={12} sm={6} md={4}>
                    <Grid container spacing={1} alignItems="flex-end">
                        <Grid item xs={6}>
                            <Stack spacing={0.25}>
                                <Typography color="text.secondary">Total Tasks</Typography>
                                <Typography variant="h5">34,686</Typography>
                            </Stack>
                        </Grid>
                        <Grid item xs={6}>
                            <TaskStatusChart color={theme.palette.primary.main} data={[5, 25, 3, 10, 4, 50, 0]} />
                        </Grid>
                    </Grid>
                </Grid>
                <Grid item xs={12} sm={6} md={4}>
                    <Grid container spacing={1}>
                        <Grid item xs={6}>
                            <Stack spacing={0.25}>
                                <Typography color="text.secondary">Pending Tasks</Typography>
                                <Typography variant="h5">3,6786</Typography>
                            </Stack>
                        </Grid>
                        <Grid item xs={6}>
                            <TaskStatusChart color={theme.palette.error.main} data={[0, 50, 4, 10, 3, 25, 5]} />
                        </Grid>
                    </Grid>
                </Grid>
                <Grid item xs={12} md={4}>
                    <Button fullWidth variant="contained" startIcon={<Add />} size="large">
                        Add project
                    </Button>
                </Grid>
            </Grid>
        </MainCard>
    );
};

export default ProjectOverview;
