// next/src/layout/Dashboard/Footer.jsx
// material-ui
import Links from '@mui/material/Link';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';

// project-imports
import { NextLink } from 'components/routes';

// ==============================|| MAIN LAYOUT - FOOTER ||============================== //

export default function Footer() {
  return (
    <Stack direction={{ sm: 'row' }} sx={{ gap: 1, justifyContent: 'space-between', alignItems: 'center', pt: 3, mt: 'auto' }}>
      <Typography variant="caption">
        &copy; Handcrafted by Team Phoenixcoded. Powered by{' '}
        <Links component={NextLink} href="https://codedthemes.com" target="_blank" underline="none">
          {' '}
          CodedThemes
        </Links>
        .
      </Typography>
      <Stack direction="row" sx={{ gap: 1.5, justifyContent: 'space-between', alignItems: 'center' }}>
        <Links component={NextLink} href="https://ableproadmin.com" target="_blank" variant="caption" color="text.primary">
          Home
        </Links>
        <Links component={NextLink} href="https://phoenixcoded.gitbook.io/able-pro" target="_blank" variant="caption" color="text.primary">
          Documentation
        </Links>
        <Links component={NextLink} href="https://codedthemes.support-hub.io/" target="_blank" variant="caption" color="text.primary">
          Support
        </Links>
      </Stack>
    </Stack>
  );
}

// angular/src/app/@theme/layouts/footer/footer.component.ts
// angular import
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-footer',
  imports: [RouterModule, CommonModule],
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {}

<footer class="theme-footer">
  <div class="footer-wrapper">
    <div class="flex align-item-center">
      <div class="col m-y-5">
        <p class="m-0">
          Able Pro crafted with &#9829; by team
          <a href="https://www.phoenixcoded.net/" target="_blank" class="text-primary-500">Phoenixcoded</a>
        </p>
      </div>
      <div class="col-auto">
        <ul class="list-inline footer-link m-b-0">
          <li class="list-inline-item"><a [routerLink]="['/']">Home</a></li>
          <li class="list-inline-item"><a href="https://phoenixcoded.gitbook.io/able-pro" target="_blank">Documentation</a></li>
          <li class="list-inline-item">
            <a href="https://codedthemes.support-hub.io/" target="_blank"> Support </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
